
#This is the configuration file for JMTB.  
#To start auto-trading a crypto-pair:


# Step One: Adding the coin properties.  Below you will see an example of sevearl coins and their properties.  
# Step Two: Add the coin to SearchCoins list.
# Step Three:  Set the E-Mail settings
# Step Four:  Verify database name.  YOu can use default, but change it to run more than one instance. 
# Step Five: System Settings.  Here you define 
# Step Six: Add your public and secret keys at the very bottom.  

coin:

    ETH: 
        period: 240 # Trading time period. In minutes. Allowed values: 5,15,30,120(2hr),240 (4hr),1440(Daily)
        auth_amt: .20 #This is the percent of the overal strategy.  Here this is %20 of my hold_pos strat.          
        enable_breakout: 0 #1 True/ 0 False
        enable_hold_pos: 1 #1 True/ 0 False
        enable_pivot: 0 #1 True/ 0 False  - This is pivot point.  Name change will come later. 
        trailing_stop: .05 #Trailing stop.  
        disable_t_stop: 1 #1 to disable.  To keep t_stop enabled (the default) set to 0
        test_trade: 0
    LTC:
        period: 30 #Trade on the 30 minute chart.
        auth_amt: .13   #Authorized .1 BTC to trade with. 
        enable_breakout: 0 #1 True/ 0 False  
        enable_hold_pos: 1 #1 True/ 0 False 
        enable_pivot: 0 #1 True/ 0 False  - This is pivot point.  Name change will come later. 
        trailing_stop: .05 #Trailing stop.  
        disable_t_stop: 1
        test_trade: 0
    SC:
        period: 1440 #Trade on the daily charts.  
        auth_amt: .03 # .03 Bitcoin worth. 
        enable_breakout: 1  #1 True / 0 False
        enable_hold_pos: 0 #1 True/ 0 False 
        enable_pivot: 0 #1 True/ 0 False  - This is pivot point.  Name change will come later. 
        trailing_stop: .05 #Trailing stop.  
        disable_t_stop: 1
        test_trade: 0

    DASH:
        period: 30
        auth_amt: .20
        enable_breakout: 0 #1 True/ 0 False
        enable_hold_pos: 1 #1 True/ 0 False
        enable_pivot: 0 #1 True/ 0 False  - This is pivot point.  Name change will come later. 
        trailing_stop: .05 #Trailing stop.  
        disable_t_stop: 1
        test_trade: 0

    LSK:
        period: 1440
        auth_amt: .21
        enable_breakout: 0 #1 True/ 0 False
        enable_hold_pos: 0 #1 True/ 0 False 
        enable_pivot: 1  #1 True/ 0 False - This is pivot point.  Name change will come later. 
        trailing_stop: .03 #Trailing stop.  
        disable_t_stop: 0
        test_trade: 0


    SYS: 
        period: 240
        auth_amt: .03 #percent
        enable_breakout: 0 #1 True/ 0 False
        enable_hold_pos: 1 #1 True/ 0 False  
        enable_pivot: 0 #1 True/ 0 False - ignore for now.  Testing.
        trailing_stop: .05 #Trailing stop.  
        disable_t_stop: 1
        test_trade: 0


    ETC: 
        period: 240
        auth_amt: .13
        enable_breakout: 0 #1 True/ 0 False
        enable_hold_pos: 1 #1 True/ 0 False  
        enable_pivot: 0 #1 True/ 0 False - ignore for now.  Testing.
        trailing_stop: .05 #Trailing stop.  
        disable_t_stop: 1
        test_trade: 0

strat_budget:
    breakout_budget: .18
    pivot_budget: .33

searchCoins: #List every coin you want to trade right here in this format.  Remove any you don't want to trade.
             # It is important to know that if the coin isn't listed here, it will not be traded at all.  
    - 'ETH'
    - 'LTC'
    - 'SC'
    - 'DASH'
    - 'LSK'
    - 'ETC'
    - 'SYS'

eMail: #DISABLED - IGNORE.
    uName: 
    auth:  
    sendTo: 
Database:
    file: 'JMTB.db'  #Self explanitory.  Just remember that this file name will need to change if you want to run multiple scripts. 

System:
    Pause_Duration: 60 #This is in seconds.  Every coin in searchcoins is queried and processed on each cycle.   
    Num_of_Cycles: 5 #The number of cycles to run.  To run just once, set to 1.  
    persistence: 1 #1 or 0.  Set to 1 to run cycles indefinately, set to 0 to repat the loop as specified above.  

Auth: 
    key: ''
    secret: ''